#!/bin/bash
#---------------------
# Testing /usr/bin/designate-* shebangs
#---------------------
set -e

BINARIES=('designate-agent' 'designate-api' 'designate-central' \
          'designate-manage' 'designate-mdns' 'designate-pool-manager' \
          'designate-producer' 'designate-rootwrap' 'designate-sink' \
          'designate-worker' 'designate-zone-manager')

ret=0

for binary in "${BINARIES[@]}"; do
    if ! `dirname $0`/test-shebang.py $binary python3.6; then
        ret=1
    fi
done

exit $ret
